export type Course = 'starter' | 'main' | 'dessert';
export type Difficulty = 'easy' | 'medium' | 'hard';

export interface Recipe {
  id: string;
  course: Course;
  name_en: string;
  name_fr: string;
  description_en: string;
  description_fr: string;
  difficulty: Difficulty;
  prepMin: number;
  cookMin: number;
  servings: number;
  ingredients_en: string[];
  ingredients_fr: string[];
  keywords: string[]; // used only for matching deal products, not displayed
}

export const RECIPES: Recipe[] = [
  // ─── STARTERS ────────────────────────────────────────────────────────────────
  {
    id: 's1', course: 'starter',
    name_en: 'Tomato & Basil Carpaccio', name_fr: 'Carpaccio de tomates au basilic',
    description_en: 'Thin-sliced ripe tomatoes with fresh basil, olive oil and fleur de sel.', description_fr: 'Fines tranches de tomates mûres, basilic frais, huile d\'olive et fleur de sel.',
    difficulty: 'easy', prepMin: 10, cookMin: 0, servings: 4,
    ingredients_en: ['Ripe tomatoes', 'Fresh basil', 'Extra-virgin olive oil', 'Fleur de sel', 'Black pepper'],
    ingredients_fr: ['Tomates mûres', 'Basilic frais', 'Huile d\'olive vierge extra', 'Fleur de sel', 'Poivre noir'],
    keywords: ['tomate'],
  },
  {
    id: 's2', course: 'starter',
    name_en: 'Courgette Velouté', name_fr: 'Velouté de courgette',
    description_en: 'Smooth, creamy courgette soup finished with crème fraîche and fresh herbs.', description_fr: 'Soupe onctueuse de courgettes, finition crème fraîche et herbes fraîches.',
    difficulty: 'easy', prepMin: 10, cookMin: 20, servings: 4,
    ingredients_en: ['Courgettes', 'Onion', 'Garlic', 'Vegetable stock', 'Crème fraîche', 'Fresh chives'],
    ingredients_fr: ['Courgettes', 'Oignon', 'Ail', 'Bouillon de légumes', 'Crème fraîche', 'Ciboulette fraîche'],
    keywords: ['courgette'],
  },
  {
    id: 's3', course: 'starter',
    name_en: 'Carrot & Ginger Soup', name_fr: 'Velouté de carottes au gingembre',
    description_en: 'Silky carrot soup with fresh ginger and a hint of coconut milk.', description_fr: 'Velouté de carottes au gingembre frais, touche de lait de coco.',
    difficulty: 'easy', prepMin: 10, cookMin: 25, servings: 4,
    ingredients_en: ['Carrots', 'Fresh ginger', 'Onion', 'Coconut milk', 'Vegetable stock', 'Olive oil'],
    ingredients_fr: ['Carottes', 'Gingembre frais', 'Oignon', 'Lait de coco', 'Bouillon de légumes', 'Huile d\'olive'],
    keywords: ['carotte'],
  },
  {
    id: 's4', course: 'starter',
    name_en: 'Gazpacho', name_fr: 'Gaspacho andalou',
    description_en: 'Classic chilled Spanish soup of tomatoes, peppers and cucumber.', description_fr: 'Soupe froide classique de tomates, poivrons et concombre.',
    difficulty: 'easy', prepMin: 15, cookMin: 0, servings: 4,
    ingredients_en: ['Ripe tomatoes', 'Red pepper', 'Cucumber', 'Garlic', 'Olive oil', 'Sherry vinegar'],
    ingredients_fr: ['Tomates mûres', 'Poivron rouge', 'Concombre', 'Ail', 'Huile d\'olive', 'Vinaigre de Xérès'],
    keywords: ['tomate', 'poivron'],
  },
  {
    id: 's5', course: 'starter',
    name_en: 'Artichoke Vinaigrette', name_fr: 'Artichauts à la vinaigrette',
    description_en: 'Whole steamed artichokes served with a Dijon mustard vinaigrette.', description_fr: 'Artichauts entiers cuits à la vapeur, vinaigrette à la moutarde de Dijon.',
    difficulty: 'easy', prepMin: 5, cookMin: 30, servings: 4,
    ingredients_en: ['Globe artichokes', 'Dijon mustard', 'Red wine vinegar', 'Olive oil', 'Shallot', 'Fresh parsley'],
    ingredients_fr: ['Artichauts', 'Moutarde de Dijon', 'Vinaigre de vin rouge', 'Huile d\'olive', 'Échalote', 'Persil frais'],
    keywords: ['artichaut'],
  },
  {
    id: 's6', course: 'starter',
    name_en: 'Melon & Cured Ham', name_fr: 'Melon au jambon cru',
    description_en: 'Sweet chilled melon paired with thinly sliced Bayonne ham.', description_fr: 'Melon frais et jambon de Bayonne finement tranché.',
    difficulty: 'easy', prepMin: 5, cookMin: 0, servings: 4,
    ingredients_en: ['Cantaloupe melon', 'Bayonne or Parma ham', 'Fresh mint', 'Black pepper'],
    ingredients_fr: ['Melon cantaloup', 'Jambon de Bayonne ou Parme', 'Menthe fraîche', 'Poivre noir'],
    keywords: ['melon'],
  },
  {
    id: 's7', course: 'starter',
    name_en: 'Endive & Roquefort Salad', name_fr: 'Salade d\'endives au roquefort',
    description_en: 'Crisp endive leaves with Roquefort, walnuts and a honey-walnut dressing.', description_fr: 'Feuilles d\'endive croquantes, roquefort, noix et vinaigrette au miel.',
    difficulty: 'easy', prepMin: 10, cookMin: 0, servings: 4,
    ingredients_en: ['Belgian endives', 'Roquefort cheese', 'Walnuts', 'Honey', 'Walnut oil', 'Cider vinegar'],
    ingredients_fr: ['Endives', 'Roquefort', 'Cerneaux de noix', 'Miel', 'Huile de noix', 'Vinaigre de cidre'],
    keywords: ['endive'],
  },
  {
    id: 's8', course: 'starter',
    name_en: 'Creamed Spinach Tartlets', name_fr: 'Tartelettes aux épinards à la crème',
    description_en: 'Buttery pastry shells filled with creamed spinach and grated nutmeg.', description_fr: 'Tartelettes beurrées garnies d\'épinards à la crème et noix de muscade.',
    difficulty: 'medium', prepMin: 20, cookMin: 20, servings: 4,
    ingredients_en: ['Shortcrust pastry', 'Fresh spinach', 'Crème fraîche', 'Nutmeg', 'Gruyère', 'Shallot'],
    ingredients_fr: ['Pâte brisée', 'Épinards frais', 'Crème fraîche', 'Noix de muscade', 'Gruyère', 'Échalote'],
    keywords: ['épinard', 'epinard'],
  },
  {
    id: 's9', course: 'starter',
    name_en: 'Leek Vinaigrette', name_fr: 'Poireaux vinaigrette',
    description_en: 'Tender braised leeks dressed with a shallot-and-herb vinaigrette.', description_fr: 'Poireaux braisés et tendres, vinaigrette échalote-herbes.',
    difficulty: 'easy', prepMin: 5, cookMin: 20, servings: 4,
    ingredients_en: ['Leeks', 'Shallot', 'Dijon mustard', 'Red wine vinegar', 'Olive oil', 'Chives'],
    ingredients_fr: ['Poireaux', 'Échalote', 'Moutarde de Dijon', 'Vinaigre de vin rouge', 'Huile d\'olive', 'Ciboulette'],
    keywords: ['poireau'],
  },
  {
    id: 's10', course: 'starter',
    name_en: 'Beef Tartare', name_fr: 'Tartare de bœuf',
    description_en: 'Hand-cut prime beef with capers, shallots, egg yolk and Tabasco.', description_fr: 'Bœuf haché au couteau, câpres, échalotes, jaune d\'œuf et Tabasco.',
    difficulty: 'medium', prepMin: 20, cookMin: 0, servings: 4,
    ingredients_en: ['Prime beef fillet', 'Capers', 'Shallot', 'Egg yolks', 'Dijon mustard', 'Tabasco', 'Cornichons'],
    ingredients_fr: ['Filet de bœuf', 'Câpres', 'Échalote', 'Jaunes d\'œuf', 'Moutarde de Dijon', 'Tabasco', 'Cornichons'],
    keywords: ['boeuf', 'bœuf', 'vache'],
  },
  {
    id: 's11', course: 'starter',
    name_en: 'Wild Mushroom Toast', name_fr: 'Fricassée de champignons sur toast',
    description_en: 'Sautéed wild mushrooms in a herb cream, served on crispy sourdough.', description_fr: 'Champignons sautés à la crème d\'herbes sur pain de campagne grillé.',
    difficulty: 'easy', prepMin: 10, cookMin: 10, servings: 4,
    ingredients_en: ['Mixed wild mushrooms', 'Garlic', 'Fresh thyme', 'Crème fraîche', 'Sourdough bread', 'Butter'],
    ingredients_fr: ['Champignons des bois mélangés', 'Ail', 'Thym frais', 'Crème fraîche', 'Pain de campagne', 'Beurre'],
    keywords: ['champignon'],
  },
  {
    id: 's12', course: 'starter',
    name_en: 'Asparagus with Hollandaise', name_fr: 'Asperges sauce hollandaise',
    description_en: 'Steamed green asparagus with a classic butter hollandaise.', description_fr: 'Asperges vertes vapeur, sauce hollandaise classique au beurre.',
    difficulty: 'medium', prepMin: 15, cookMin: 15, servings: 4,
    ingredients_en: ['Green asparagus', 'Egg yolks', 'Clarified butter', 'Lemon juice', 'White wine vinegar'],
    ingredients_fr: ['Asperges vertes', 'Jaunes d\'œuf', 'Beurre clarifié', 'Jus de citron', 'Vinaigre de vin blanc'],
    keywords: ['asperge'],
  },
  {
    id: 's13', course: 'starter',
    name_en: 'Strawberry & Burrata', name_fr: 'Salade fraises burrata',
    description_en: 'Fresh strawberries and creamy burrata with balsamic glaze and basil.', description_fr: 'Fraises fraîches, burrata crémeuse, balsamique réduit et basilic.',
    difficulty: 'easy', prepMin: 10, cookMin: 0, servings: 4,
    ingredients_en: ['Fresh strawberries', 'Burrata', 'Balsamic glaze', 'Fresh basil', 'Olive oil', 'Fleur de sel'],
    ingredients_fr: ['Fraises fraîches', 'Burrata', 'Réduction de balsamique', 'Basilic frais', 'Huile d\'olive', 'Fleur de sel'],
    keywords: ['fraise'],
  },

  // ─── MAINS ───────────────────────────────────────────────────────────────────
  {
    id: 'm1', course: 'main',
    name_en: 'Rack of Lamb with Herbs', name_fr: 'Carré d\'agneau aux herbes',
    description_en: 'Herb-crusted rack of lamb roasted to perfection, served with a rosemary jus.', description_fr: 'Carré d\'agneau en croûte d\'herbes, jus au romarin.',
    difficulty: 'medium', prepMin: 15, cookMin: 25, servings: 4,
    ingredients_en: ['Rack of lamb', 'Breadcrumbs', 'Fresh rosemary', 'Fresh thyme', 'Garlic', 'Dijon mustard', 'Olive oil'],
    ingredients_fr: ['Carré d\'agneau', 'Chapelure', 'Romarin frais', 'Thym frais', 'Ail', 'Moutarde de Dijon', 'Huile d\'olive'],
    keywords: ['agneau'],
  },
  {
    id: 'm2', course: 'main',
    name_en: 'Slow-Braised Lamb Shoulder', name_fr: 'Épaule d\'agneau confite',
    description_en: '7-hour slow-roasted lamb shoulder with garlic and thyme, fall-off-the-bone tender.', description_fr: 'Épaule d\'agneau confite 7 heures à l\'ail et au thym.',
    difficulty: 'easy', prepMin: 10, cookMin: 420, servings: 6,
    ingredients_en: ['Lamb shoulder', 'Garlic cloves', 'Fresh thyme', 'Rosemary', 'Olive oil', 'White wine', 'Onion'],
    ingredients_fr: ['Épaule d\'agneau', 'Gousses d\'ail', 'Thym frais', 'Romarin', 'Huile d\'olive', 'Vin blanc', 'Oignon'],
    keywords: ['agneau'],
  },
  {
    id: 'm3', course: 'main',
    name_en: 'Spring Lamb Navarin', name_fr: 'Navarin d\'agneau printanier',
    description_en: 'Classic French lamb stew with spring vegetables — carrots, turnips and peas.', description_fr: 'Ragoût d\'agneau aux légumes de printemps : carottes, navets et petits pois.',
    difficulty: 'medium', prepMin: 20, cookMin: 90, servings: 4,
    ingredients_en: ['Lamb shoulder pieces', 'Carrots', 'Turnips', 'Peas', 'Onion', 'Tomato paste', 'Bouquet garni'],
    ingredients_fr: ['Morceaux d\'épaule d\'agneau', 'Carottes', 'Navets', 'Petits pois', 'Oignon', 'Concentré de tomate', 'Bouquet garni'],
    keywords: ['agneau', 'carotte'],
  },
  {
    id: 'm4', course: 'main',
    name_en: 'Roast Beef with Pan Jus', name_fr: 'Rôti de bœuf au jus',
    description_en: 'Classic roast beef cooked to a blush pink, with a rich pan jus.', description_fr: 'Rôti de bœuf rosé à cœur, jus de cuisson réduit.',
    difficulty: 'medium', prepMin: 10, cookMin: 60, servings: 6,
    ingredients_en: ['Beef roasting joint', 'Garlic', 'Fresh thyme', 'Butter', 'Beef stock', 'Shallots', 'Red wine'],
    ingredients_fr: ['Rôti de bœuf', 'Ail', 'Thym frais', 'Beurre', 'Fond de bœuf', 'Échalotes', 'Vin rouge'],
    keywords: ['boeuf', 'bœuf', 'vache'],
  },
  {
    id: 'm5', course: 'main',
    name_en: 'Provençal Beef Daube', name_fr: 'Daube de bœuf provençale',
    description_en: 'Slow-cooked beef in red wine with olives, orange peel and herbes de Provence.', description_fr: 'Bœuf braisé au vin rouge, olives, zeste d\'orange et herbes de Provence.',
    difficulty: 'medium', prepMin: 20, cookMin: 180, servings: 6,
    ingredients_en: ['Beef chuck', 'Red wine', 'Black olives', 'Orange peel', 'Herbes de Provence', 'Carrots', 'Onion'],
    ingredients_fr: ['Bœuf paleron', 'Vin rouge', 'Olives noires', 'Zeste d\'orange', 'Herbes de Provence', 'Carottes', 'Oignon'],
    keywords: ['boeuf', 'bœuf', 'vache'],
  },
  {
    id: 'm6', course: 'main',
    name_en: 'Veal Blanquette', name_fr: 'Blanquette de veau à l\'ancienne',
    description_en: 'Tender veal in a velvety cream sauce with button mushrooms and pearl onions.', description_fr: 'Veau fondant en sauce veloutée, champignons de Paris et petits oignons.',
    difficulty: 'medium', prepMin: 20, cookMin: 90, servings: 4,
    ingredients_en: ['Veal shoulder', 'Button mushrooms', 'Pearl onions', 'Crème fraîche', 'Egg yolks', 'Lemon', 'Bouquet garni'],
    ingredients_fr: ['Épaule de veau', 'Champignons de Paris', 'Petits oignons grelots', 'Crème fraîche', 'Jaunes d\'œuf', 'Citron', 'Bouquet garni'],
    keywords: ['veau', 'champignon'],
  },
  {
    id: 'm7', course: 'main',
    name_en: 'Veal Piccata', name_fr: 'Escalopes de veau au citron',
    description_en: 'Pan-fried veal escalopes in a lemon-caper-butter sauce.', description_fr: 'Escalopes de veau sautées, sauce citron-câpres-beurre.',
    difficulty: 'easy', prepMin: 10, cookMin: 15, servings: 4,
    ingredients_en: ['Veal escalopes', 'Lemon', 'Capers', 'Butter', 'White wine', 'Flour', 'Fresh parsley'],
    ingredients_fr: ['Escalopes de veau', 'Citron', 'Câpres', 'Beurre', 'Vin blanc', 'Farine', 'Persil frais'],
    keywords: ['veau'],
  },
  {
    id: 'm8', course: 'main',
    name_en: 'Ratatouille', name_fr: 'Ratatouille niçoise',
    description_en: 'The Provençal classic — layers of courgette, aubergine, peppers and tomatoes in olive oil.', description_fr: 'La niçoise par excellence : courgette, aubergine, poivron et tomate confits à l\'huile d\'olive.',
    difficulty: 'easy', prepMin: 20, cookMin: 60, servings: 4,
    ingredients_en: ['Courgettes', 'Aubergine', 'Red pepper', 'Tomatoes', 'Onion', 'Garlic', 'Olive oil', 'Herbes de Provence'],
    ingredients_fr: ['Courgettes', 'Aubergine', 'Poivron rouge', 'Tomates', 'Oignon', 'Ail', 'Huile d\'olive', 'Herbes de Provence'],
    keywords: ['courgette', 'aubergine', 'poivron', 'tomate'],
  },
  {
    id: 'm9', course: 'main',
    name_en: 'Stuffed Peppers', name_fr: 'Poivrons farcis',
    description_en: 'Bell peppers stuffed with seasoned rice, herbs and a hint of tomato.', description_fr: 'Poivrons garnis de riz assaisonné, herbes fraîches et coulis de tomate.',
    difficulty: 'easy', prepMin: 20, cookMin: 40, servings: 4,
    ingredients_en: ['Bell peppers', 'Long-grain rice', 'Tomatoes', 'Onion', 'Garlic', 'Fresh parsley', 'Olive oil'],
    ingredients_fr: ['Poivrons', 'Riz long', 'Tomates', 'Oignon', 'Ail', 'Persil frais', 'Huile d\'olive'],
    keywords: ['poivron'],
  },
  {
    id: 'm10', course: 'main',
    name_en: 'Courgette & Goat\'s Cheese Gratin', name_fr: 'Gratin de courgettes au chèvre',
    description_en: 'Thinly sliced courgettes layered with cream, garlic and crumbled goat\'s cheese.', description_fr: 'Courgettes en lamelles, crème, ail et fromage de chèvre émietté gratinés.',
    difficulty: 'easy', prepMin: 15, cookMin: 30, servings: 4,
    ingredients_en: ['Courgettes', 'Goat\'s cheese', 'Crème fraîche', 'Garlic', 'Fresh thyme', 'Olive oil'],
    ingredients_fr: ['Courgettes', 'Fromage de chèvre', 'Crème fraîche', 'Ail', 'Thym frais', 'Huile d\'olive'],
    keywords: ['courgette'],
  },
  {
    id: 'm11', course: 'main',
    name_en: 'Tian Provençal', name_fr: 'Tian provençal',
    description_en: 'Oven-roasted rounds of courgette, tomato and aubergine with olive oil and thyme.', description_fr: 'Courgettes, tomates et aubergines en rondelles, thym, confites au four.',
    difficulty: 'easy', prepMin: 20, cookMin: 45, servings: 4,
    ingredients_en: ['Courgettes', 'Tomatoes', 'Aubergine', 'Garlic', 'Fresh thyme', 'Olive oil', 'Parmesan'],
    ingredients_fr: ['Courgettes', 'Tomates', 'Aubergine', 'Ail', 'Thym frais', 'Huile d\'olive', 'Parmesan'],
    keywords: ['courgette', 'tomate', 'aubergine'],
  },
  {
    id: 'm12', course: 'main',
    name_en: 'Mushroom Risotto', name_fr: 'Risotto aux champignons',
    description_en: 'Creamy arborio rice with sautéed wild mushrooms, white wine and Parmesan.', description_fr: 'Riz arborio crémeux, champignons sautés, vin blanc et parmesan.',
    difficulty: 'medium', prepMin: 10, cookMin: 30, servings: 4,
    ingredients_en: ['Arborio rice', 'Mixed mushrooms', 'Shallots', 'White wine', 'Parmesan', 'Vegetable stock', 'Butter'],
    ingredients_fr: ['Riz arborio', 'Champignons mélangés', 'Échalotes', 'Vin blanc', 'Parmesan', 'Bouillon de légumes', 'Beurre'],
    keywords: ['champignon'],
  },
  {
    id: 'm13', course: 'main',
    name_en: 'French Green Bean Salad', name_fr: 'Salade de haricots verts tièdes',
    description_en: 'Blanched green beans with shallots, Dijon vinaigrette and crispy lardons.', description_fr: 'Haricots verts blanchis, échalotes, vinaigrette Dijon et lardons croustillants.',
    difficulty: 'easy', prepMin: 10, cookMin: 10, servings: 4,
    ingredients_en: ['Green beans', 'Lardons', 'Shallot', 'Dijon mustard', 'Red wine vinegar', 'Walnut oil'],
    ingredients_fr: ['Haricots verts', 'Lardons', 'Échalote', 'Moutarde de Dijon', 'Vinaigre de vin rouge', 'Huile de noix'],
    keywords: ['haricot'],
  },
  {
    id: 'm14', course: 'main',
    name_en: 'Duck Breast with Strawberry Sauce', name_fr: 'Magret de canard aux fraises',
    description_en: 'Pan-seared duck breast with a strawberry and balsamic reduction.', description_fr: 'Magret de canard poêlé, réduction fraise-balsamique.',
    difficulty: 'medium', prepMin: 10, cookMin: 20, servings: 4,
    ingredients_en: ['Duck breast', 'Fresh strawberries', 'Balsamic vinegar', 'Honey', 'Butter', 'Shallot', 'Fresh thyme'],
    ingredients_fr: ['Magret de canard', 'Fraises fraîches', 'Vinaigre balsamique', 'Miel', 'Beurre', 'Échalote', 'Thym frais'],
    keywords: ['fraise'],
  },
  {
    id: 'm15', course: 'main',
    name_en: 'Spinach & Potato Gratin', name_fr: 'Gratin dauphinois aux épinards',
    description_en: 'Creamy layered potato gratin with wilted spinach and Gruyère.', description_fr: 'Gratin dauphinois aux épinards tombés et Gruyère fondu.',
    difficulty: 'easy', prepMin: 20, cookMin: 50, servings: 4,
    ingredients_en: ['Potatoes', 'Fresh spinach', 'Gruyère', 'Double cream', 'Garlic', 'Nutmeg', 'Butter'],
    ingredients_fr: ['Pommes de terre', 'Épinards frais', 'Gruyère', 'Crème entière', 'Ail', 'Noix de muscade', 'Beurre'],
    keywords: ['épinard', 'epinard', 'pomme de terre'],
  },

  // ─── DESSERTS ─────────────────────────────────────────────────────────────────
  {
    id: 'd1', course: 'dessert',
    name_en: 'Cherry Clafoutis', name_fr: 'Clafoutis aux cerises',
    description_en: 'The Limousin classic — fresh cherries baked in a vanilla custard batter.', description_fr: 'Le classique limousin : cerises fraîches cuites dans une pâte crémeuse à la vanille.',
    difficulty: 'easy', prepMin: 10, cookMin: 35, servings: 6,
    ingredients_en: ['Fresh cherries', 'Eggs', 'Whole milk', 'Sugar', 'Flour', 'Vanilla extract', 'Butter'],
    ingredients_fr: ['Cerises fraîches', 'Œufs', 'Lait entier', 'Sucre', 'Farine', 'Extrait de vanille', 'Beurre'],
    keywords: ['cerise'],
  },
  {
    id: 'd2', course: 'dessert',
    name_en: 'Apricot Tart', name_fr: 'Tarte aux abricots',
    description_en: 'Buttery shortcrust pastry with almond cream and caramelised fresh apricots.', description_fr: 'Pâte sablée beurrée, crème d\'amande et abricots frais caramélisés.',
    difficulty: 'medium', prepMin: 30, cookMin: 35, servings: 8,
    ingredients_en: ['Shortcrust pastry', 'Fresh apricots', 'Ground almonds', 'Butter', 'Sugar', 'Eggs', 'Vanilla'],
    ingredients_fr: ['Pâte sablée', 'Abricots frais', 'Poudre d\'amandes', 'Beurre', 'Sucre', 'Œufs', 'Vanille'],
    keywords: ['abricot'],
  },
  {
    id: 'd3', course: 'dessert',
    name_en: 'Apricot Crumble', name_fr: 'Crumble aux abricots',
    description_en: 'Warm apricot compote topped with a golden buttery crumble.', description_fr: 'Compote d\'abricots tiède sous un crumble doré et beurré.',
    difficulty: 'easy', prepMin: 15, cookMin: 25, servings: 6,
    ingredients_en: ['Fresh apricots', 'Butter', 'Plain flour', 'Caster sugar', 'Ground almonds', 'Cinnamon'],
    ingredients_fr: ['Abricots frais', 'Beurre', 'Farine', 'Sucre', 'Poudre d\'amandes', 'Cannelle'],
    keywords: ['abricot'],
  },
  {
    id: 'd4', course: 'dessert',
    name_en: 'Strawberry Tart', name_fr: 'Tarte aux fraises',
    description_en: 'Crisp pastry shell, vanilla pastry cream and a crown of fresh strawberries.', description_fr: 'Fond de tarte croustillant, crème pâtissière vanille et couronne de fraises fraîches.',
    difficulty: 'medium', prepMin: 40, cookMin: 20, servings: 8,
    ingredients_en: ['Shortcrust pastry', 'Fresh strawberries', 'Egg yolks', 'Whole milk', 'Sugar', 'Vanilla pod', 'Cornflour'],
    ingredients_fr: ['Pâte sablée', 'Fraises fraîches', 'Jaunes d\'œuf', 'Lait entier', 'Sucre', 'Gousse de vanille', 'Maïzena'],
    keywords: ['fraise'],
  },
  {
    id: 'd5', course: 'dessert',
    name_en: 'Strawberries with Chantilly', name_fr: 'Fraises à la chantilly',
    description_en: 'Fresh strawberries macerated with sugar and lemon, served with whipped cream.', description_fr: 'Fraises fraîches macérées sucre-citron, chantilly maison.',
    difficulty: 'easy', prepMin: 10, cookMin: 0, servings: 4,
    ingredients_en: ['Fresh strawberries', 'Double cream', 'Icing sugar', 'Vanilla extract', 'Lemon zest'],
    ingredients_fr: ['Fraises fraîches', 'Crème entière', 'Sucre glace', 'Extrait de vanille', 'Zeste de citron'],
    keywords: ['fraise'],
  },
  {
    id: 'd6', course: 'dessert',
    name_en: 'Honey-Roasted Peaches', name_fr: 'Pêches rôties au miel',
    description_en: 'Peach halves roasted with honey, vanilla and a splash of kirsch.', description_fr: 'Demi-pêches rôties au miel, vanille et kirsch.',
    difficulty: 'easy', prepMin: 5, cookMin: 20, servings: 4,
    ingredients_en: ['Fresh peaches', 'Honey', 'Vanilla pod', 'Kirsch', 'Butter', 'Flaked almonds'],
    ingredients_fr: ['Pêches fraîches', 'Miel', 'Gousse de vanille', 'Kirsch', 'Beurre', 'Amandes effilées'],
    keywords: ['pêche', 'peche', 'nectarine'],
  },
  {
    id: 'd7', course: 'dessert',
    name_en: 'Peach Melba', name_fr: 'Pêche Melba',
    description_en: 'Poached peaches on vanilla ice cream with a fresh raspberry coulis.', description_fr: 'Pêches pochées sur glace vanille, coulis de framboises fraîches.',
    difficulty: 'easy', prepMin: 15, cookMin: 10, servings: 4,
    ingredients_en: ['Fresh peaches', 'Vanilla ice cream', 'Fresh raspberries', 'Sugar', 'Vanilla pod', 'Lemon juice'],
    ingredients_fr: ['Pêches fraîches', 'Glace vanille', 'Framboises fraîches', 'Sucre', 'Gousse de vanille', 'Jus de citron'],
    keywords: ['pêche', 'peche', 'nectarine', 'framboise'],
  },
  {
    id: 'd8', course: 'dessert',
    name_en: 'Melon Sorbet', name_fr: 'Sorbet melon',
    description_en: 'Intensely flavoured melon sorbet, refreshing and naturally sweet.', description_fr: 'Sorbet melon au goût intense, rafraîchissant et naturellement sucré.',
    difficulty: 'easy', prepMin: 15, cookMin: 0, servings: 4,
    ingredients_en: ['Cantaloupe melon', 'Sugar', 'Lemon juice', 'Fresh mint'],
    ingredients_fr: ['Melon cantaloup', 'Sucre', 'Jus de citron', 'Menthe fraîche'],
    keywords: ['melon'],
  },
  {
    id: 'd9', course: 'dessert',
    name_en: 'Raspberry Tart', name_fr: 'Tarte aux framboises',
    description_en: 'Crisp pastry with lemon cream and fresh raspberries.', description_fr: 'Fond de tarte croustillant, crème citron et framboises fraîches.',
    difficulty: 'medium', prepMin: 40, cookMin: 20, servings: 8,
    ingredients_en: ['Shortcrust pastry', 'Fresh raspberries', 'Lemon curd', 'Double cream', 'Icing sugar'],
    ingredients_fr: ['Pâte sablée', 'Framboises fraîches', 'Lemon curd', 'Crème entière', 'Sucre glace'],
    keywords: ['framboise'],
  },
  {
    id: 'd10', course: 'dessert',
    name_en: 'Pear Belle-Hélène', name_fr: 'Poire Belle-Hélène',
    description_en: 'Poached pear with warm chocolate sauce and vanilla ice cream.', description_fr: 'Poire pochée, sauce chocolat chaude et glace vanille.',
    difficulty: 'easy', prepMin: 10, cookMin: 15, servings: 4,
    ingredients_en: ['Pears', 'Dark chocolate', 'Double cream', 'Vanilla ice cream', 'Sugar', 'Vanilla pod'],
    ingredients_fr: ['Poires', 'Chocolat noir', 'Crème entière', 'Glace vanille', 'Sucre', 'Gousse de vanille'],
    keywords: ['poire'],
  },
  {
    id: 'd11', course: 'dessert',
    name_en: 'Grape & Almond Tart', name_fr: 'Tarte raisin-amande',
    description_en: 'Almond frangipane tart topped with fresh grapes.', description_fr: 'Tarte à la crème d\'amande garnie de raisins frais.',
    difficulty: 'medium', prepMin: 30, cookMin: 35, servings: 8,
    ingredients_en: ['Shortcrust pastry', 'Fresh grapes', 'Ground almonds', 'Butter', 'Sugar', 'Eggs'],
    ingredients_fr: ['Pâte sablée', 'Raisins frais', 'Poudre d\'amandes', 'Beurre', 'Sucre', 'Œufs'],
    keywords: ['raisin'],
  },
];
